/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplosformularios.refrigeradora;

/**
 *
 * @author sergio.mendez
 */
public class FrmRefri extends javax.swing.JFrame {
    public Refrigeradora mirefri=new Refrigeradora();

    /**
     * Creates new form FrmRefri
     */
    public FrmRefri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComidaPreparada = new javax.swing.JButton();
        btnVerdura = new javax.swing.JButton();
        btnFruta = new javax.swing.JButton();
        btnBebida = new javax.swing.JButton();
        btnCarne = new javax.swing.JButton();
        btnSalsa = new javax.swing.JButton();
        btnSacarAlimento = new javax.swing.JButton();
        btnMostrarAlimentos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreAlimento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenidoRefrigeradora = new javax.swing.JTextArea();
        JLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEnvejecer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnComidaPreparada.setText("+Comida Preparada");
        btnComidaPreparada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComidaPreparadaActionPerformed(evt);
            }
        });

        btnVerdura.setText("+Verdura");
        btnVerdura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerduraActionPerformed(evt);
            }
        });

        btnFruta.setText("+Fruta");
        btnFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrutaActionPerformed(evt);
            }
        });

        btnBebida.setText("+Bebida");
        btnBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidaActionPerformed(evt);
            }
        });

        btnCarne.setText("+Carne");
        btnCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarneActionPerformed(evt);
            }
        });

        btnSalsa.setText("+Salsa");
        btnSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalsaActionPerformed(evt);
            }
        });

        btnSacarAlimento.setText("SacarAlimento");

        btnMostrarAlimentos.setText("Mostrar Alimentos");
        btnMostrarAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAlimentosActionPerformed(evt);
            }
        });

        jLabel1.setText("Alimento");

        contenidoRefrigeradora.setColumns(20);
        contenidoRefrigeradora.setRows(5);
        jScrollPane1.setViewportView(contenidoRefrigeradora);

        JLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        JLabel2.setText("Refrigeradora");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEnvejecer.setText("Envejecer Alimentos");
        btnEnvejecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvejecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBebida)
                .addGap(377, 377, 377))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(JLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSacarAlimento)
                                .addGap(73, 73, 73)
                                .addComponent(btnMostrarAlimentos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(nombreAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEnvejecer))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnComidaPreparada)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCarne)
                            .addComponent(btnVerdura))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnFruta))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnSalsa))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel2)
                    .addComponent(btnSalir))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComidaPreparada)
                    .addComponent(btnVerdura)
                    .addComponent(btnFruta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBebida)
                            .addComponent(btnSalsa))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCarne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnvejecer))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarAlimentos)
                    .addComponent(btnSacarAlimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnComidaPreparadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComidaPreparadaActionPerformed
        // TODO add your handling code here:
        mirefri.meterAlimento(new ComidaPreparada( nombreAlimento.getText() ));
        contenidoRefrigeradora.setText("");
        contenidoRefrigeradora.append("Agregue ComidaPreparada");

    }//GEN-LAST:event_btnComidaPreparadaActionPerformed

    private void btnVerduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerduraActionPerformed
        // TODO add your handling code here:
        contenidoRefrigeradora.setText("");
        mirefri.meterAlimento(new Verdura( nombreAlimento.getText() ));
        contenidoRefrigeradora.append("Agregue Verdura");
    }//GEN-LAST:event_btnVerduraActionPerformed

    private void btnFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrutaActionPerformed
        // TODO add your handling code here:
        contenidoRefrigeradora.setText("");
        mirefri.meterAlimento(new Fruta( nombreAlimento.getText() ));
        contenidoRefrigeradora.append("Agregue Fruta");
    }//GEN-LAST:event_btnFrutaActionPerformed

    private void btnBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidaActionPerformed
        // TODO add your handling code here:
        contenidoRefrigeradora.setText("");
        mirefri.meterAlimento(new Bebida( nombreAlimento.getText() ));
        contenidoRefrigeradora.append("Agregue Bebida");
    }//GEN-LAST:event_btnBebidaActionPerformed

    private void btnCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarneActionPerformed
        // TODO add your handling code here:
        contenidoRefrigeradora.setText("");
        mirefri.meterAlimento(new Carne( nombreAlimento.getText() ));
        contenidoRefrigeradora.append("Agregue Carne");
    }//GEN-LAST:event_btnCarneActionPerformed

    private void btnSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalsaActionPerformed
        // TODO add your handling code here:
        contenidoRefrigeradora.setText("");
        mirefri.meterAlimento(new Salsa( nombreAlimento.getText() ));
        contenidoRefrigeradora.append("Agregue Salsa");
    }//GEN-LAST:event_btnSalsaActionPerformed

    private void btnMostrarAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAlimentosActionPerformed
        // TODO add your handling code here:
        contenidoRefrigeradora.setText(mirefri.mostrarAlimentos());
    }//GEN-LAST:event_btnMostrarAlimentosActionPerformed

    private void btnEnvejecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvejecerActionPerformed
        // TODO add your handling code here:
        mirefri.envejecerAlimentos();
    }//GEN-LAST:event_btnEnvejecerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRefri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRefri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRefri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRefri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRefri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel2;
    private javax.swing.JButton btnBebida;
    private javax.swing.JButton btnCarne;
    private javax.swing.JButton btnComidaPreparada;
    private javax.swing.JButton btnEnvejecer;
    private javax.swing.JButton btnFruta;
    private javax.swing.JButton btnMostrarAlimentos;
    private javax.swing.JButton btnSacarAlimento;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalsa;
    private javax.swing.JButton btnVerdura;
    private javax.swing.JTextArea contenidoRefrigeradora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreAlimento;
    // End of variables declaration//GEN-END:variables
}
